name: Test
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    outputs:
      finish: ${{ steps.run-build.outputs.finish }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Python 2.x
        id: run-build
        run: |
          python3 build.py

  build2:
    runs-on: windows-latest
    needs: build
    outputs:
      finish: ${{ steps.run-build.outputs.finish }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Python 2.x
        id: run-build
        run: |
          python3 build.py
